1.Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.
Delete the found duplicate file.
[Hint: use hashlib]


In [3]:
import os , hashlib
from pathlib import Path
path = "C:/Users/kgoyal/OneDrive - ALLEGIS GROUP/Documents/"

file_list = os.walk(path)

unique = dict()
for root,folders,files in file_list:
    for file in files:
        path = Path(os.path.join(root,file))
        fileHash = hashlib.sha256(open(path,'rb').read()).hexdigest()
        print(len(fileHash))
        if fileHash not in unique:
            unique[fileHash] = path
            
        else:
            os.remove(path)
            print(f"{path} has been deleted")

32
32
32
32
32
C:\Users\kgoyal\OneDrive - ALLEGIS GROUP\Documents\newfile1.txt has been deleted
32
32
32
32
32
C:\Users\kgoyal\OneDrive - ALLEGIS GROUP\Documents\afterSentDocuments\docs0\abc0.doc has been deleted
32
C:\Users\kgoyal\OneDrive - ALLEGIS GROUP\Documents\afterSentDocuments\docs0\abc2.doc has been deleted
32
C:\Users\kgoyal\OneDrive - ALLEGIS GROUP\Documents\afterSentDocuments\docs0\abc3.doc has been deleted
32
C:\Users\kgoyal\OneDrive - ALLEGIS GROUP\Documents\afterSentDocuments\docs0\abc4.doc has been deleted
32
32
C:\Users\kgoyal\OneDrive - ALLEGIS GROUP\Documents\afterSentDocuments\docs0\def1.txt has been deleted
32
C:\Users\kgoyal\OneDrive - ALLEGIS GROUP\Documents\afterSentDocuments\docs0\def2.txt has been deleted
32
C:\Users\kgoyal\OneDrive - ALLEGIS GROUP\Documents\afterSentDocuments\docs0\def3.txt has been deleted
32
C:\Users\kgoyal\OneDrive - ALLEGIS GROUP\Documents\afterSentDocuments\docs0\def4.txt has been deleted
32
32
C:\Users\kgoyal\OneDrive - ALLEGIS GROUP\Do

2. Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]


In [4]:
import random
import string
up = string.ascii_uppercase
low =string.ascii_lowercase
dig = string.digits
spc = string.punctuation
upper =[]
lower = []
digit = []
special_char = []
for i in up:
    upper.append(i)
for i in low:
    lower.append(i)
for i in dig:
    digit.append(i)
for i in spc:
    special_char.append(i)
password = random.choices(upper,k=1)+random.choices(lower,k=2)+random.choices(digit,k=2)+random.choices(special_char,k=1)
pass1 = ""
random.shuffle(password)
for i in password:
    pass1+=i
print("a strong password of length 6 for you - ",pass1)


a strong password of length 6 for you -  6Ob^f8


3.	Create 2D array and 
update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [5]:
import numpy as np
x = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]
l = len(x)
r = len(x[0])

def isprime(num):
    if(num ==0 or num==1):
        return False
    for j in range(2,int(num/2)+1):
        if(num%j == 0):
            return False
    return True

list1 = [j for sub in x for j in sub]

primeposition =[]
for i in range(len(list1)):
    if isprime(i) == True:
        list1[i] = list1[i]**3
        primeposition.append(i)
final = np.array(list1).reshape(l,r)
print(final)

[[   0    1    8   27]
 [   4  125    6  343]
 [   8    9   10 1331]]


4.	Python program to get the sum of every cubed value and its previous integer. 

In [6]:
list2 = [p for element in final for p in element]
temp = list2[primeposition[0]-1]
for i in range(len(list2)):
    k= list2[i]
    if(i in primeposition ):
        list2[i] +=temp
    temp = k
result = np.array(list2).reshape(l,r)
print(result)

[[   0    1    9   35]
 [   4  129    6  349]
 [   8    9   10 1341]]


5.	Given two arrays, find their intersection. Examples:

Input:  arr1[] = [1, 3, 4, 5, 7]
             arr2[] = [2, 3, 5, 6]


In [7]:

arr1 = set([1, 3, 4, 5, 7] )
arr2 = set([2, 3, 5, 6])
print(arr1.intersection(arr2))

{3, 5}


6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [8]:
import numpy as np
size = 7*7
list1 = []
for i in range(1,size+1):
    list1.append(7*i)
arr_multipleOf7 = np.array(list1).reshape(7,7)
print(arr_multipleOf7[-1,-1])

343


In [10]:
i = int(input("enter the no. rows"))
j = int(input("enter the no. columns"))
matrix = np.ones((i,j),dtype = 'int16')
matrix[1::2,0::2] =0
matrix[0::2,1::2] = 0 
print(matrix)

enter the no. rows7
enter the no. columns8
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [11]:
vowels = ['A', 'E', 'I', 'O','U','a','e','i','o','u']
alpha =[  ['A','B','C','D'],
   ['E','F','G','H'],
    ['I','a','K','L'],
   ['M','N','o','P'],
   ['Q','R','S','T'],
   ['U','0','W','O']]
for i in range(len(alpha)):
    for j in range(len(alpha[0])):
        if(alpha[i][j] in vowels):
            alpha[i][j] = np.nan
print(alpha)
c = 0
for i in range(len(alpha)):
    c +=alpha[i].count(np.nan)
print(c)      

[[nan, 'B', 'C', 'D'], [nan, 'F', 'G', 'H'], [nan, nan, 'K', 'L'], ['M', 'N', nan, 'P'], ['Q', 'R', 'S', 'T'], [nan, '0', 'W', nan]]
7
